AWSTemplateFormatVersion: 2010-09-09
Description: App1
Parameters: 
  InstanceType:
    Type: String
  SGGroupName:
    Type: String
Resources: 
  App1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: craig-desktop
      ImageId: ami-0bae7412735610274
      InstanceType: !Ref InstanceType
      Monitoring: false
      SecurityGroupIds:
        - !Ref secGroupName
  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref AWS::StackName
      GroupDescription: !Ref SGGroupName
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          CidrIp: 0.0.0.0/0